apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: omar-web-proxy-app
    template: omar-web-proxy-app-template
  name: omar-web-proxy-app
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-tcp
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    deploymentconfig: omar-web-proxy-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
  