
version: '3'
services:
  services:
    image: quay.io/radiantsolutions/omar-services-app:latest
    restart: always
    volumes:
      - ./sanfrancisco:/data/sanfrancisco
      - ./elevation:/data/elevation
      - ./application_services.yml:/home/omar/application.yml
    environment:
      - OSSIM_DATA=/data
      - SPRING_CLOUD_DISCOVERY_ENABLED=false
    depends_on:
      - database
    ports:
      - 9090:9090

  tlv:
    image: quay.io/radiantsolutions/tlv-app:latest
    restart: always
    environment:
      - SPRING_CLOUD_DISCOVERY_ENABLED=false
    volumes:
      - ./application_tlv.yml:/home/omar/application.yml
    depends_on:
      - services
      - twofishes

  twofishes:
    image: quay.io/radiantsolutions/omar-twofishes:latest
    restart: always
    environment:
      - SPRING_CLOUD_DISCOVERY_ENABLED=false
    depends_on:
      - services
      - database

  ui:
    image: quay.io/radiantsolutions/omar-ui-app:latest
    restart: always
    environment:
      - SPRING_CLOUD_DISCOVERY_ENABLED=false
    depends_on:
      - services
    volumes:
      - ./application_ui.yml:/home/omar/application.yml

  database:
    image: quay.io/radiantsolutions/postgres-postgis-trgm:latest
    restart: always
    environment:
      - POSTGRES_DB=omar-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  apache:
    image: httpd:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./o2-proxy.conf:/usr/local/apache2/conf/o2-proxy.conf
