version: '3'
services:
  nginx:
    image: nginx:latest
    networks:
      - proxynet
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ui

networks:
  proxynet:
    name: proxynet
	
