#
# This is a sample storage class that changes the paramters passed to the heketi service 
# allowing one to create a none replicating volume.  This storage class type is 
# referenced via the name glusterfs-dynamic-norep
#
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: glusterfs-dynamic-norep
    namespace: ""
  parameters:
    resturl: http://heketi-dynamic.glusterfs.svc:8080
    restuser: admin
    secretName: heketi-dynamic-admin-secret
    secretNamespace: glusterfs
    volumetype: "none"
  provisioner: kubernetes.io/glusterfs
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""