apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: kibana
  labels:
    app: kibana
    deploymentconfig: kibana
spec:
  replicas: KIBANA_REPLICAS
  revisionHistoryLimit: 10
  selector:
    name: kibana
    deploymentconfig: kibana
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  triggers:
    - type: "ConfigChange"
  template:
    metadata:
      labels:
        name: kibana
        deploymentconfig: kibana
    spec:
      containers:
      - env:
          - name: cluster.name
            value: es-cluster
          - name: bootstrap.memory_lock
            value: "false"
          - name: node.master
            value: "false"
          - name: node.data
            value: "false"
          - name: node.ingest
            value: "false"
          - name: cluster.remote.connect
            value: "false"
          - name: discovery.zen.ping.unicast.hosts
            value: "CLUSTER_LOCATIONS"
          - name: discovery.zen.minimum_master_nodes
            value: "1"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
        image: ES_IMAGE
        imagePullPolicy: Always
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: rest-internal
          protocol: TCP
      - env:
          - name: ELASTICSEARCH_URL
            value: https://localhost:9200
          # If we are going through a proxy and we want a basepath add this
          # so it matches the proxy
          #
          # - name: SERVER_BASEPATH
          #   value: /kibana
        image: KIBANA_IMAGE
        imagePullPolicy: Always
        name: kibana
        ports:
        - containerPort: 5601
          name: rest
          protocol: TCP
